WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import include, path
from catalog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

WebBooks/catalog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books-list'),
    path('books/<int:pk>/', views.BookDetailView.as_view(),
        name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors-list'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(),
        name='authors-detail'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(),
        name='my-borrowed'),
    path('edit_authors/', views.edit_authors, name='edit_authors'),
    path('authors_add/', views.add_author, name='authors_add'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('edit_author/<int:id>/', views.edit_author, name='edit_author'),
    path('edit_books/', views.edit_books, name='edit_books'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/update/<int:pk>/', views.BookUpdate.as_view(),
        name='book_update'),
    path('book/delete/<int:pk>/', views.BookDelete.as_view(),
        name='book_delete'),
]

WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200,
        help_text=" Введите жанр книги",
        verbose_name="Жанр книги")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=20,
        help_text=" Введите язык книги",
        verbose_name="Язык книги")
    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=20,
        help_text=" Введите наименование издательства",
        verbose_name="Издательство")
    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100,
        help_text="Введите имя автора",
        verbose_name="Имя автора")
    last_name = models.CharField(max_length=100,
        help_text="Введите фамилию автора",
        verbose_name="Фамилия автора")
    date_of_birth = models.DateField(
        help_text="Введите дату рождения",
        verbose_name="Дата рождения",
        null=True, blank=True)
    about = models.TextField(help_text="Введите сведения об авторе",
        verbose_name="Сведения об авторе")
    photo = models.ImageField(upload_to='images',
        help_text="Введите фото автора",
        verbose_name="Фото автора",
        null=True, blank=True)

    def __str__(self):
        return self.last_name

class Book(models.Model):
    title = models.CharField(max_length=200,
        help_text="Введите название книги",
        verbose_name="Название книги")
    genre = models.ForeignKey('Genre',
        on_delete=models.CASCADE,
        help_text=" Выберите жанр для книги",
        verbose_name="Жанр книги", null=True)
    language = models.ForeignKey('Language',
        on_delete=models.CASCADE,
        help_text="Выберите язык книги",
        verbose_name="Язык книги", null=True)
    publisher = models.ForeignKey('Publisher',
        on_delete=models.CASCADE,
        help_text="Выберите издательство",
        verbose_name="Издательство", null=True)
    year = models.CharField(max_length=4,
        help_text="Введите год издания",
        verbose_name="Год издания")
    author = models.ManyToManyField('Author',
        help_text="Выберите автора (авторов) книги",
        verbose_name="Автор (авторы) книги")
    summary = models.TextField(max_length=1000,
        help_text="Введите краткое описание книги",
        verbose_name="Аннотация книги")
    isbn = models.CharField(max_length=13,
        help_text="Должно содержать 13 символов",
        verbose_name="ISBN книги")
    price = models.DecimalField(decimal_places=2, max_digits=7,
        help_text="Введите цену книги",
        verbose_name="Цена (руб.)")
    photo = models.ImageField(upload_to='images',
        help_text="Введите изображение обложки",
        verbose_name="Изображение обложки")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in
                          self.author.all()])
    display_author.short_description = 'Авторы'

class Status(models.Model):
    name = models.CharField(max_length=20,
        help_text="Введите статус экземпляра книги",
        verbose_name="Статус экземпляра книги")

    def __str__(self):
        return self.name

class BookInstance(models.Model):
 book = models.ForeignKey('Book',
 on_delete=models.CASCADE, null=True)
 inv_nom = models.CharField(
 max_length=20,
 null=True,
 help_text="Введите инвентарный номер экземпляра",
 verbose_name="Инвентарный номер")
 status = models.ForeignKey('Status',
 on_delete=models.CASCADE,
 null=True,
 help_text='Изменить состояние экземпляра',
 verbose_name="Статус экземпляра книги")
 due_back = models.DateField(null=True,
 blank=True,
 help_text="Введите конец срока статуса",
 verbose_name="Дата окончания статуса")
 borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
 null=True, blank=True,
 verbose_name="Заказчик",
 help_text='Выберите заказчика книги')
 objects = models.Manager

 @property
 def is_overdue(self):
     if self.due_back and date.today() > self.due_back:
         return True
     return False

 # Метаданные
 class Meta:
    ordering = ["due_back"]
 def __str__(self):
    return '%s %s %s' % (self.inv_nom, self.book, self.status)

WebBooks/catalog/forms.py
from django import forms
from datetime import date
from .models import Book
# форма для добавления в БД новых авторов
class Form_add_author(forms.Form):
 first_name = forms.CharField(label="Имя автора")
 last_name = forms.CharField(label="Фамилия автора")
 date_of_birth = forms.DateField(
 label="Дата рождения",
 initial=format(date.today()),
 widget=forms.widgets.DateInput(attrs={'type': 'date'}))
 about = forms.CharField(label="Сведения об авторе",
 widget=forms.Textarea)
 photo = forms.ImageField(label="Фото автора")

class BookModelForm(forms.ModelForm):
 class Meta:
  model = Book
  fields = '__all__'

WebBooks/catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Author
from .forms import forms
from .forms import Form_add_author
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'

class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 3

def index(request):
    text_head = 'На нашем сайте вы можете получить книги в электронном виде'
    books = Book.objects.all()
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact=2).count()

    authors = Author.objects
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {'text_head': text_head,
        'books': books, 'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'authors': authors, 'num_authors': num_authors,
        'num_visits': num_visits}

    return render(request, 'catalog/index.html', context)

class AuthorListView(ListView):
    model = Author
    paginate_by = 4

class AuthorDetailView(DetailView):
    model = Author

def about(request):
    text_head = 'Сведения о компании'
    name = 'ООО "Интеллектуальные информационные системы"'
    rab1 = 'Разработка приложений на основе' \
    ' систем искусственного интеллекта'
    rab2 = 'Распознавание объектов дорожной инфраструктуры'
    rab3 = 'Создание графических АРТ-объектов на основе' \
    ' систем искусственного интеллекта'
    rab4 = 'Создание цифровых интерактивных книг, учебных пособий' \
    ' автоматизированных обучающих систем'
    context = {'text_head': text_head, 'name': name,
    'rab1': rab1, 'rab2': rab2,
    'rab3': rab3, 'rab4': rab4}
    return render(request, 'catalog/about.html', context)

def contact(request):
    text_head = 'Контакты'
    name = 'ООО "Интеллектуальные информационные системы"'
    address = 'Москва, ул. Планерная, д.20, к.1'
    tel = '495-345-45-45'
    email = 'iis_info@mail.ru'
    context = {'text_head': text_head,
    'name': name, 'address': address,
    'tel': tel,
    'email': email}
    return render(request, 'catalog/contact.html', context)

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
 # Универсальный класс представления списка книг,
 # находящихся в заказе у текущего пользователя
 model = BookInstance
 template_name = 'catalog/bookinstance_list_borrowed_user.html'
 paginate_by = 10

 def get_queryset(self):
    return BookInstance.objects.filter(
        borrower=self.request.user).filter(
        status__exact='2').order_by('due_back')

def edit_authors(request):
 author = Author.objects.all()
 context = {'author': author}
 return render(request, "catalog/edit_authors.html", context)


def add_author(request):
    if request.method == 'POST':
        form = Form_add_author(request.POST, request.FILES)
        if form.is_valid():
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            date_of_birth = form.cleaned_data.get("date_of_birth")
            about = form.cleaned_data.get("about")
            photo = form.cleaned_data.get("photo")
            obj = Author.objects.create(
                 first_name=first_name,
                 last_name=last_name,
                 date_of_birth=date_of_birth,
                 about=about,
                 photo=photo)
            obj.save()
            return HttpResponseRedirect(reverse('authors-list'))
        else:
            form = Form_add_author()
            context = {"form": form}
            return render(request, "catalog/authors_add.html", context)

def delete(request, id):
 try:
    author = Author.objects.get(id=id)
    author.delete()
    return HttpResponseRedirect("/edit_authors/")
 except:
    return HttpResponseNotFound("<h2>Автор не найден</h2>")

class Form_edit_author(forms.ModelForm):
 class Meta:
    model = Author
    fields = '__all__'

def edit_author(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        instance = Author.objects.get(pk=id)
        form = Form_edit_author(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/edit_authors/")
    else:
        form = Form_edit_author(instance=author)
        content = {"form": form}
        return render(request, "catalog/edit_author.html", content)

    return HttpResponse("Invalid request")  # Добавленный код


def edit_books(request):
 book = Book.objects.all()
 context = {'book': book}
 return render(request, "catalog/edit_books.html", context)

class BookCreate(CreateView):
 model = Book
 fields = '__all__'
 success_url = reverse_lazy('edit_books')
# Класс для обновления в БД записи о книге
class BookUpdate(UpdateView):
 model = Book
 fields = '__all__'
 success_url = reverse_lazy('edit_books')
# Класс для удаления из БД записи о книге
class BookDelete(DeleteView):
 model = Book
 success_url = reverse_lazy('edit_books')

WebBooks/templates/catalog/about.html
{% extends "base.html" %}
<head>
{% load static %}
</head>
{% block content %}
<!-- Карусель -->
<div class="container">
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
<div class="carousel-inner">
<div class="carousel-item active">
<img src="{% static 'images/ai.jpg' %}" style="height: 200px;" class="d-block w-100 " alt="image">
<div class="carousel-caption d-none d-md-block">
<h2 class="text-white">Искусственный интеллект</h2>
<h3 class="text-white">{{rab1}}</h3>
</div>
</div>
<div class="carousel-item">
<img src="{% static 'images/road.jpg' %}" style="height: 200px;" class="d-block w-100 " alt="image">
<div class="carousel-caption d-none d-md-block">
<h2 class="text-white">Компьютерное зрение</h2>
<h3 class="text-white">{{rab2}}</h3>
</div>
</div>
<div class="carousel-item">
<img src="{% static 'images/art.jpg' %}" style="height: 200px;" class="d-block w-100 " alt="image">
<div class="carousel-caption d-none d-md-block">
<h2 class="text-white">Арт объекты</h2>
<h3 class="text-white">{{rab3}}</h3>
</div>
</div>
<div class="carousel-item">
<img src="{% static 'images/ebook.jpg' %}" style="height: 200px;" class="d-block w-100 " 
alt="image">
<div class="carousel-caption d-none d-md-block">
<h2 class="text-white">Электронные книги</h2>
<h3 class="text-white">{{rab4}}</h3>
</div>
</div>
</div>
<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bsslide="prev">
<span class="carousel-control-prev-icon" aria-hidden="true"></span>
<span class="visually-hidden">Предыдущий</span>
</button>
<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bsslide="next">
<span class="carousel-control-next-icon" aria-hidden="true"></span>
<span class="visually-hidden">Следующий</span>
</button>
</div>
</div>
<!-- Конец карусели -->
<div class="container-fluid">
<h4 class="text-center">{{ text_head }}</h4>
<div class="row my-2 text-center">
<div class="col-5"></div>
<div class="col-1 text-center">
<img src="{% static 'images/SIS.jpg' %}" width="250" height="250">
</div>
<div class="col-5"></div>
</div>
<div class="row my-2 text-primary text-center">
<h3>{{ name }}</h3>
</div>
<div class="row my-2 text-white text-start">
<div class="col mx-2 my-2 bg-primary">{{rab1}}</div>
<div class="col mx-2 my-2 bg-primary">{{rab2}}</div>
<div class="col mx-2 my-2 bg-primary">{{rab3}}</div>
<div class="col mx-2 my-2 bg-primary">{{rab4}}</div>
</div>
</div>
<div class="row my-2 text-center">
<!-- пустые колонки слева от аккордеона-->
<div class="col-3"></div>
<!-- 6 колонок с аккордеоном -->
<div class="col-6 text-start">
<!-- Аккордеон -->
<div class="accordion" id="accordionExample">
<!-- Аккордеон элемент 1-->
<div class="accordion-item">
<h2 class="accordion-header" id="headingOne">
<button class="accordion-button" type="button"
data-bs-toggle="collapse"
data-bs-target="#collapseOne"
aria-expanded="true" aria-controls="collapseOne">
Искусственный интеллект
</button>
</h2>
<div id="collapseOne" class="accordion-collapse collapse"
aria-labelledby="headingOne" data-bs-parent="#accordionExample">
<div class="accordion-body">
<strong>Разработка под ключ.</strong> Разрабатываем
информационные комплексы на базе систем
искусственного интеллекта.
</div>
</div>
</div>
<!-- Аккордеон элемент 2-->
<div class="accordion-item">
<h2 class="accordion-header" id="headingTwo">
<button class="accordion-button collapsed" type="button"
data-bs-toggle="collapse" data-bs-target="#collapseTwo"
aria-expanded="false" aria-controls="collapseTwo">
Дорожная инфраструктура
</button>
</h2>
<div id="collapseTwo" class="accordion-collapse collapse"
aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
<div class="accordion-body">
<strong>Системы распознавания.</strong> Разрабатываем системы
распознавания объектов дорожной инфраструктуры с
использованием нейронных сетей.
</div>
</div>
</div>
<!-- Аккордеон элемент 3-->
<div class="accordion-item">
<h2 class="accordion-header" id="headingThree">
<button class="accordion-button collapsed" type="button"
data-bs-toggle="collapse"
data-bs-target="#collapseThree"
aria-expanded="false" aria-controls="collapseThree">
Арт объекты
</button>
</h2>
<div id="collapseThree" class="accordion-collapse collapse"
aria-labelledby="headingThree" data-bs-parent="#accordionExample">
<div class="accordion-body">
<strong>Обработка изображений.</strong> Создаем уникальные
изображения с использованием систем машинного зрения
и искусственного интеллекта.
</div>
</div>
<!-- Аккордеон элемент 4-->
<div class="accordion-item">
<h2 class="accordion-header" id="headingFour">
<button class="accordion-button collapsed" type="button"
data-bs-toggle="collapse"
data-bs-target="#collapseFour"
aria-expanded="false" aria-controls="collapseThree">
Интерактивные электронные книги
</button>
</h2>
<div id="collapseFour" class="accordion-collapse collapse"
aria-labelledby="headingFour" data-bs-parent="#accordionExample">
<div class="accordion-body">
<strong>Интерактивное обучение</strong> Разрабатываем интерактивные
обучающие пособия, учебники, электронные книги для студентов
и школьников.
</div>
</div>
</div>
<!-- Аккордеон конец-->
</div>
</div>
<!-- пустые колонки справа от аккордеона-->
<div class="col-3"></div>
</div>
{% endblock %}

WebBooks/templates/catalog/author_add.html
{% extends "base.html" %}
{% block content %}
<h5>Добавить в БД автора книги</h5>
<form action="" method="POST" enctype="multipart/form-data">
 {% csrf_token %}
 <div class="row">
 <div class="col-2 "></div>
 <div class="col-8 ">
 <table class="table text-start">
 {{ form }}
 </table>
 </div>
 <div class="col-2"></div>
 </div>
 <input type="submit" value="Сохранить" >
</form>
{% endblock %}

WebBooks/templates/catalog/author_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container text-start">
<div class="row my-2">
<h4>{{ object.first_name }} {{author.last_name}}</h4>
<p>Родился - {{author.date_of_birth}}</p>
<p>Фото (портрет)</p>
<p><img src="{{ author.photo.url }}"
alt="connect" style="max-height:200px"></p>
<div class="row my-2">
<div class="col-2 my-2">
<a href="{{ author.photo.url}}" class="btn btn-primary"
target="_blank"> Показать</a>
</div>
</div>
<div class="row my-2">
{{author.about}}
</div>
</div> 
</div>
{% endblock %}

WebBooks/templates/catalog/author_list.html
{% extends "base.html" %}
{% block content %}
<h4>Список авторов книг</h4>
{% if author_list %}
<table class="table table-striped table-bordered text-start">
<thead>
<tr>
<th>Автор</th>
<th>Фото</th>
<th>Показать фото</th>
</tr>
</thead>
<tbody>
{% for author in author_list.all %}
<tr>
<td><a href="{{ author.id }}">{{ author.first_name}}
{{author.last_name}} </a></td>
<td><img src="{{ author.photo.url }}" alt="connect"
style="max-height:100px"></td>
<td><a href="{{ author.photo.url}}"
class="btn btn-primary"
target="_blank"> Показать</a></td>
</tr>
{% endfor %}
<tbody>
</table>
{% else %}
<p>В базе данных нет авторов</p>
{% endif %}
{% endblock %}

WebBooks/templates/catalog/book_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Удаление книги</h1>
<p> Вы уверены, что хотите удалить книгу: {{ book }}?</p>
<form action="" method="POST" enctype="multipart/form-data">
 {% csrf_token %}
 <input type="submit" action="" value="Да, удалить" />
</form>
{% endblock %}

WebBooks/templates/catalog/book_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container text-start">
<div class="row my-2">
<h1>Название книги - "{{ book.title }}"</h1>
</div>
<div class="row my-2">
<p><strong>Автор:</strong>
{% for author in book.author.all %}
<a href="/authors/{{ author.id }}">
{{ author.first_name }} {{author.last_name}}</a>
{% endfor %}
</div>
<img src="{{ book.photo.url }}" alt="connect"
style="max-height:200px">
<a href="{{ book.photo.url}}"
class="btn btn-primary"
target="_blank"> Показать</a>
<div class="row my-2">
<div class="col">
<p><strong>Цена:</strong> {{ book.price }} руб.</p>
</div>
</div>
<div class="row my-2">
<p><strong>Аннотация:</strong> {{ book.summary }}</p>
</div>
<div class="row my-2">
<div class="col mx-2 bg-primary text-white">
<p><strong>Жанр:</strong> {{ book.genre }}</p>
</div>
<div class="col mx-2 bg-primary text-white">
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
</div>
<div class="col mx-2 bg-primary text-white">
<p><strong>Язык:</strong> {{ book.language }}</p>
</div>
<div class="col mx-2 bg-primary text-white">
<p><strong>Издательство:</strong> {{book.publisher}}</p>
</div>
</div>
<div style="margin-left:20px; margin-top:10px">
<h4>Количество экземпляров книг в БД</h4>
{% for copy in book.bookinstance_set.all %}
<hr>
<p class="text-muted">
<strong>Инвентарный номер:</strong> {{copy.id}}</p>
<p class="text-success">
<strong>Статус экземпляра книги:</strong> {{copy.status}}</p>
{% endfor %}
</div>
</div>
{% endblock %}

WebBooks/templates/catalog/book_form.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
 {% csrf_token %}
 <table class="text-start">
 {{ form.as_table }}
 </table>
 <input type="submit" value="Сохранить" />
</form>
{% endblock %}

WebBooks/templates/catalog/book_list.html
{% extends "base.html" %}
{% block content %}
<div class="row text-center text-dark lh-2">
<h4>Список книг в БД</h4>
</div>
{% if books %}
<table class="table table-striped table-bordered text-start">
<thead>
<tr>
<th>Название</th>
<th>Автор</th>
<th>Жанр</th>
<th>Обложка</th>
<th>Показать обложку</th>
</tr>
</thead>
<tbody>
{% for book in books %}
<tr>
<td><a href="{{ book.id }}">{{ book.title }} </a></td>
<td>{{ book.display_author }}</td>
<td>{{ book.genre }}</td>
<td><img src="{{ book.photo.url }}" alt="connect"
style="max-height:100px"></td>
<td><a href="{{ book.photo.url}}"
class="btn btn-primary"
target="_blank"> Показать</a></td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
<p>В базе данных нет книг</p>
{% endif %}
{% endblock %}

WebBooks/templates/catalog/bookinstance_list_borrowed_user.html
<{% extends "base.html" %}
{% block content %}
 <h1>Взятые книги</h1>
 {% if bookinstance_list %}
 {% for bookinst in bookinstance_list %}
 <div class="{% if bookinst.is_overdue %} text-danger{% endif %}">
 <a href="{% url 'book-detail' bookinst.book.pk %}">
 {{bookinst.book.title}}</a>
 {{ bookinst.due_back }}
 </div>
 {% endfor %}
 {% else %}
 <p>Нет книг со статусом В ЗАКАЗЕ.</p>
 {% endif %}
{% endblock %}

WebBooks/templates/catalog/contact.html
{% extends "base.html" %}
<head>
{% load static %}
</head>
{% block content %}
<div class="container-fluid">
<div class="row my-2 text-center">
<div class="col-5"></div>
<div class="col-1 text-center">
<img src="{% static 'images/SIS.jpg' %}" width="250" height="250">
</div>
<div class="col-5"></div>
</div>
<div class="row my-2 text-primary text-center">
<h3>{{ name }}</h3>
</div>
<div class="row my-2 text-muted ">
<h4 class="text-center">{{ text_head }}</h4>
</div>
<div class="row my-2">
<!-- пустые колонки слева от таблицы-->
<div class="col-3"></div>
<div class="col-6">
<table class="table table-striped table-bordered text-start">
<thead>
<tr>
<th>Адрес</th>
<th>Телефон</th>
<th>e-mail</th>
</tr>
</thead>
<tbody>
<tr>
<td>{{ address }}</td>
<td>{{ tel }}</td>
<td>{{ email }}</td>
</tr>
<tbody>
</table>
</div>
<!-- пустые колонки справа от таблицы-->
<div class="col-3"></div>
<!-- карта-->
<div class="row my-2 text-center">
<div class="col-2"></div>
<div class="col-8">
<img src="{% static 'images/SIS.jpg' %}" class="img-fluid" width="250" height="250">
</div>
<div class="col-2"></div>
</div>

</div>
{% endblock %}

WebBooks/templates/catalog/edit_author.html
{% extends "base.html" %}
{% block content %}
<div class="row text-start lh-2">
 <h3>Изменить сведения об авторе</h3>
</div>
<form method="post" enctype="multipart/form-data">
 {% csrf_token %}
 <table class="text-start">
 {% for field in form %}
 <tr>
 <th>{{ field.label_tag }}
 {{ field.errors }}
 </th>
 <th>{{ field }}</th>
 </tr>
 {% endfor %}
 <th>
 <button type="submit">Сохранить</button>
 </th>
 </table>
</form>
{% endblock %}

WebBooks/templates/catalog/edit_authors.html
{% extends "base.html" %}
{% block content %}
<div class="row text-start lh-2">
 <h5>Список авторов для редактирования</h5>
</div>
 <div class="row">
 <div class="col-2 "></div>
 <a href="/authors_add/{{authors_add}}">Добавить автора</a>
 <div class="col-8 ">
 <table class="table table-striped table-bordered text-start">
 <thead>
 <tr>
 <th>Id</th>
 <th>Имя</th>
 <th>Фамилия</th>
 <th>Редактировать</th>
 </tr>
 </thead>
 <tbody>
 {% if author %}
 {% for author in author.all %}
 <tr>
 <td>{{author.id}}</td>
 <td>{{author.first_name}}</td>
 <td>{{author.last_name}}</td>
 <td><a href="/edit_author/{{author.id}}">Изменить</a> ,
 <a href="/delete/{{author.id}}">Удалить</a></td>
 </tr>
 {% endfor %}
 {% else %}
 <p> В базе данных нет авторов</p>
 {% endif %}
 <tbody>
 </table>
 </div>
 <div class="col-2"></div>
 </div>
{% endblock %}

WebBooks/templates/catalog/edit_books.html
{% extends "base.html" %}
{% block content %}
<div class="row text-start lh-2">
 <h5>Список книг для редактирования</h5>
</div>
 <div class="row">
 <div class="col-2 "></div>
 <a href="{% url 'book_create' %}">Добавить книгу</a>
 <div class="col-8 ">
 <table class="table table-striped table-bordered text-start">
 <thead>
 <tr>
 <th>Id</th>
 <th>Название книги</th>
 <th>Редактировать</th>
 </tr>
 </thead>
 <tbody>
 {% if book %}
 {% for book in book.all %}
 <tr>
 <td>{{book.id}}</td>
 <td>{{book.title}}</td>
 <td><a href="/book/update/{{book.id}}">Изменить</a> ,
 <a href="/book/delete/{{book.id}}">Удалить</a></td>
 </tr>
 {% endfor %}
 {% else %}
 <p> В базе данных нет книг</p>
 {% endif %}
 <tbody>
 </table>
 </div>
 <div class="col-2"></div>
 </div>
{% endblock %}